ARG GO_IMAGE
FROM ${GO_IMAGE} AS build
WORKDIR /src
COPY gateway/ ./
RUN CGO_ENABLED=0 go build -mod=readonly -trimpath -ldflags='-s -w' -o /gateway . \
    && CGO_ENABLED=0 go build -mod=readonly -trimpath -ldflags='-s -w' -o /faucet ./cmd/faucet \
    && mkdir /data
RUN mkdir /licenses \
    && cp /usr/local/go/LICENSE /licenses/LICENSE.go \
    && go list -m -f '{{if .Dir}}{{.Path}} {{.Version}} {{.Dir}}{{end}}' all | \
       while read -r module version directory; do \
         if [ -n "$directory" ]; then \
           for file in "$directory"/LICENSE* "$directory"/COPYING* "$directory"/NOTICE*; do \
             if [ -f "$file" ]; then \
               mkdir -p "/licenses/$module@$version"; \
               cp "$file" "/licenses/$module@$version/"; \
             fi; \
           done; \
         fi; \
       done
FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /gateway /gateway
COPY --from=build /faucet /faucet
COPY --from=build /licenses /licenses
COPY --from=build --chown=65532:65532 /data /data
USER 65532:65532
ENTRYPOINT ["/gateway"]
